name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv (fast installer) and dependencies
        run: |
          pip install -U pip
          pip install -U pytest black isort ruff pre-commit

      - name: Run linters
        run: |
          ruff check .
          black --check .
          isort --check-only .

      - name: Run tests
        run: |
          pytest -q
